name: master
on:
  push:
    branches:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: sam build
      
      - name: Package
        run: sam package --resolve-s3 --region ap-south-1 --output-template-file output-template.yaml
      
      - name: Deploy
        run: sam deploy --stack-name AwsSamDemo --template-file output-template.yaml --region ap-south-1 --capabilities CAPABILITY_IAM --parameter-overrides ApiGatewayEndpointType=REGIONAL TargetEnvironment=prod
